# Generated by Django 5.1 on 2025-03-24 01:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0009_alter_cart_user'),
        ('shop', '0005_product_trending'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('abandoned', models.BooleanField(default=True)),
                ('converted_to_order', models.BooleanField(default=False)),
                ('conversion_time', models.DateTimeField(blank=True, null=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('wishlist_adds', models.PositiveIntegerField(default=0)),
                ('cart_adds', models.PositiveIntegerField(default=0)),
                ('cart_conversions', models.PositiveIntegerField(default=0)),
                ('wishlist_conversions', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='analytics_d_date_24cb73_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('wishlist_adds', models.PositiveIntegerField(default=0)),
                ('cart_adds', models.PositiveIntegerField(default=0)),
                ('cart_conversions', models.PositiveIntegerField(default=0)),
                ('wishlist_conversions', models.PositiveIntegerField(default=0)),
                ('average_session_duration', models.DurationField(default=datetime.timedelta(0))),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'month'], name='analytics_m_year_c6d95b_idx')],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('session_key', models.CharField(max_length=40)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField()),
                ('referrer', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='analytics_p_timesta_835321_idx'), models.Index(fields=['path'], name='analytics_p_path_3382b5_idx'), models.Index(fields=['session_key'], name='analytics_p_session_1f2553_idx')],
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('converted_to_cart', models.BooleanField(default=False)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items_analytics', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
