# Generated by Django 5.1 on 2025-03-29 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_pageview_is_unique_pageview_session_duration_and_more'),
        ('shop', '0009_rename_on_new_product_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='page_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pageview', to='shop.product'),
        ),
    ]
