# Generated by Django 5.2 on 2025-04-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_pageview_page_type_pageview_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
