# Generated by Django 5.1 on 2025-03-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_sale_end_date_product_sale_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_new',
            field=models.BooleanField(default=False),
        ),
    ]
