# Generated by Django 5.1 on 2024-08-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_moto',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
