# Generated by Django 5.1 on 2025-03-29 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_on_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='on_new',
            new_name='is_new',
        ),
    ]
