# Generated by Django 5.2 on 2025-05-28 12:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_product_photo_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
