# Generated by Django 5.1 on 2025-03-24 02:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='is_unique',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='session_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='session_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='session_start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
