# Generated by Django 5.1 on 2025-03-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected',
            field=models.BooleanField(default=True),
        ),
    ]
