# Generated by Django 5.1 on 2025-03-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cartitem_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
