# Generated by Django 5.2 on 2025-04-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_cartitem_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='selected',
        ),
    ]
