# Generated by Django 5.1 on 2024-08-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('JazzCash', 'JazzCash')], max_length=30),
        ),
    ]
