# Generated by Django 5.1 on 2025-03-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_fix_tracking_number_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default=None, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
