# Generated by Django 5.1 on 2025-03-29 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_tracking_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tracking_number',
            new_name='order_number',
        ),
    ]
